In [5]:
from scipy.signal import StateSpace
import numpy as np

In [16]:
from scipy.signal import StateSpace

# Parameters

n = 1000
d_x = 2
d_y = 5
dt = 0.01

rng = np.random.default_rng(0)


# Initialze State-Space Matrices
A = np.array([[0.9, -0.2],
              [0.2,  0.8]])

C = np.random.randn(d_y, d_x)
B = np.zeros((d_x, 1))
D = np.zeros((d_y, 1))


# Define the Discrete-Time State-Space System
sys = StateSpace(A, B, C, D, dt=dt)

rng = np.random.default_rng(0)


# Noise levels
epsilon_t = 0.1  # process noise
heta_t = 0.2  # observation noise


# Allocate arrays
x = np.zeros((n, d_x))  # state trajectory
y = np.zeros((n, d_y))  # observed time series

# Initial state
x[0] = rng.normal(size=d_x)


# Simulating the system 

for t in range(1, n):
    x[t] = A @ x[t-1] + sigma_x * rng.normal(size=d_x)
    y[t] = C @ x[t]   + sigma_y * rng.normal(size=d_y)



# Spectral radius (should be < 1 for stability)
print("Spectral radius:", np.max(np.abs(np.linalg.eigvals(A))))

# Shapes
print("x shape:", x.shape)
print("y shape:", y.shape)



Spectral radius: 0.8717797887081348
x shape: (1000, 2)
y shape: (1000, 5)


In [17]:
print(sys)

StateSpaceDiscrete(
array([[ 0.9, -0.2],
       [ 0.2,  0.8]]),
array([[0.],
       [0.]]),
array([[ 3.33964383e-01,  5.34294483e-02],
       [-1.64163636e-03,  9.12017423e-01],
       [ 5.32247807e-01, -4.62360950e-01],
       [-3.72991892e-01, -2.08560106e+00],
       [-2.74342514e-01, -1.09579096e+00]]),
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]]),
dt: 0.01
)
